### ISSUE TITLE
Take photo with volume button

### ISSUE THREAD

**Issue by Magissia** [SimpleMobileTools/Simple-Camera#11]
Hello, it would be nice to be able to take photos using volume button

**Comment by tibbi** [comment]
ah no, I dont like it when I press the volume and the camera takes a picture.. Volume is there for volume, use the display or hardware button (if you have) for taking pictures :)

**Comment by Magissia** [comment]
Be able doesn't means force, could be something the user can set in settings, mobile with dedicated photo physical button are rare... Pressing the screen reduce stability, who likes blurry photos ?
