### ISSUE TITLE
Flash should be configurable while image capturing

### ISSUE THREAD

**Issue by jigarpatel17** [SimpleMobileTools/Simple-Camera#114]
This is just an idea.

As of now, when we enable flash while capturing image from back camera, it directly starts flash and it remain continuously ON.

We should have an option which let us switch on flash either in continuous mode or switch on flash when image is going to be captured.

**Comment by tibbi** [comment]
if you try toggling flash again, isnt there an Auto mode? With an "A" letter at the icon.

**Comment by jigarpatel17** [comment]
Yes, it's true. Thanks. Apologies for typo.
