### ISSUE TITLE
Save photo in DCIM folder

### ISSUE THREAD

**Issue by sanpii** [SimpleMobileTools/Simple-Camera#12]
Can you follow the standard to improve interoperability with others applications?

**Comment by tibbi** [comment]
makes sense, I will add an option to set the save directory. For example I like that its not the default DCIM :)

**Comment by tibbi** [comment]
made saving in DCIM the default now, can be turned off in settings. I will add some more advanced folder picker in the future.

**Comment by sanpii** [comment]
Thank you :smiley:
