### ISSUE TITLE
Front/back camera button switches between the two back lenses only [OnePlus 5]

### ISSUE THREAD

**Issue by 80tf3262p8** [SimpleMobileTools/Simple-Camera#128]
The OnePlus 5 has two different lenses on the back. (I think one is a macro lens.) When I press the camera switch button it toggles between these two lenses; I cannot switch to the front camera. It's kind of cool since I haven't used another app that can do this, but at the same time, it's not really the expected behavior.

This happens in Lineage OS 15.1 (also happened in 14); not sure how the stock OxygenOS handles it.

**Comment by tibbi** [comment]
The Camera has been rewritten from scratch under the hood in version 4.1.0, please update whenever it becomes available and create a new ticket if you are still having issues.
