### ISSUE TITLE
New logo proposal 

### ISSUE THREAD

**Issue by liobash** [SimpleMobileTools/Simple-Camera#133]
Hi, i have been using a copy of this app for a while now and i thought of creating a new and amazing logo for it since i have the skills to.. just want to send you a sample, and let me know if you like it, then i will proceed with the uploading of the remaining necessary files to google cloud memory so that you can download and implement. Bellow is the sample.
https://i.imgur.com/9ltKv8j.png
https://i.imgur.com/guyoqct.png
https://i.imgur.com/pTsWLEx.png
Let me know what you think

**Comment by tibbi** [comment]
Hey, thanks for the effort, but those logos are way too complicated. Anyway I currently dont plan changing the logo.
