### ISSUE TITLE
User is not informed when taking a photo 

### ISSUE THREAD

**Issue by F3000** [SimpleMobileTools/Simple-Camera#145]
Please add a little white flash after taking a photo .
I have my phone muted and don’t see any action when I take a photo

**Comment by tibbi** [comment]
well you can see the bottom icons disappear for a moment

**Comment by F3000** [comment]
I haven’t recognized it yet. Maybe you can implement this is future releases

**Comment by MisterY** [comment]
I would second this request. The sound is too loud (not configurable) for indoor shooting so I keep it off. But then there is no obvious sign that a photo has been taken.
Will try the recommendation above but it would be great if there was some explicit visual sign on the screen.
It could be a flash, image border, animation, anything really.

**Comment by MisterY** [comment]
The icons disappearing is not bad but also not obvious to new users. People tend to focus on what's on the camera viewer, not on the buttons under their fingers. That is not intuitive at all, unfortunately.
