### ISSUE TITLE
Camera flash setting changes when switching from video to photos

### ISSUE THREAD

**Issue by esmoak** [SimpleMobileTools/Simple-Camera#150]
Simple Camera: 4.0.0 from F-Droid

Steps to reproduce:
1) Open Simple Camera.
2) Switch flash mode to Auto (Lightning bolt with 'A' on it).
3) Switch to video mode (Flash defaults to off).
4) Switch back to camera photo mode and **the flash is now off instead of in auto.**

I'm assuming this is a bug because:
1) Open Simple Camera and switch flash mode to auto while in photo mode.
2) Close Simple Camera.
3) Re-open Camera and flash is still in auto in photo mode.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
