### ISSUE TITLE
Add Option to set preview size. (feature request)

### ISSUE THREAD

**Issue by ulqu3** [SimpleMobileTools/Simple-Camera#157]
Option to set preview size (standard or full screen)

**Comment by tibbi** [comment]
preview size depends on the picked resolution

**Comment by ulqu3** [comment]
How do you pick resolution?

**Comment by tibbi** [comment]
press the button on the main screen under toggling photo/video, by 2 under settings

**Comment by ulqu3** [comment]
Tried it, the back camera maxed out at 9.4MP while my phone is capable of 13MP
Front camera was up to full capacity 5MP
Video resolution in both front at back was pegged at 2.1MP

**Comment by tibbi** [comment]
well resolutions given by the device are listed there, Im not tweaking them in any way, just sorting
