### ISSUE TITLE
Camera button does not work

### ISSUE THREAD

**Issue by pager72** [SimpleMobileTools/Simple-Camera#160]
My phone, like many others have a dedicated button to launch camera and take photos. Currently the app does not recognise this button and pressing it does not take photos.

**Comment by tibbi** [comment]
If you want to launch this app at pressing the hardware camera button, you might have to disable the built in Camera app in Settings -> Apps -> Camera -> Disable. If it doesnt work, does it work at any other camera than the stock one?

**Comment by pager72** [comment]
The trouble is the app doesn't take photos using the camera button. Launching the app with a camera button is not the issue.

**Comment by tibbi** [comment]
The Camera has been rewritten from scratch under the hood in version 4.1.0, please create a new ticket if you are still having issues.
