### ISSUE TITLE
Camera button does not work - doesn't work for 4.1.0 also

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Camera#167]
My phone, like many others have a dedicated button to launch camera and take photos. Currently the app does not recognise this button and pressing it does not take photos.

**Comment by tibbi** [comment]
does it work in any downloaded app and not a stock app? Can you maybe try OpenCamera?

**Comment by tibbi** [comment]
well it might be some system limitation then which sends the trigger to stock apps only. What device do you have exactly?

**Comment by pager72** [comment]
Ulefone armor 2 with Android 7.0

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
