### ISSUE TITLE
Pictures are saved 90° clockwise

### ISSUE THREAD

**Issue by mrvanes** [SimpleMobileTools/Simple-Camera#171]
All pictures are rotated 90° right relative to the orientation of the phone.
Phone: Alcatel Idol 2 Mini S (6036Y)
Version: Android 6.0.1
Kernel: 3.10.49

**Comment by tibbi** [comment]
what app version?

**Comment by mrvanes** [comment]
4.1.1 12 june 2018.

**Comment by tibbi** [comment]
do other Camera apps work fine? Did it work well in the previous app version, or are you a new user?

**Comment by Kingwad** [comment]
Same bug. Moto Z. Oreo 8.0.0.

4.0.0 worked correctly.
4.1.1 images would not register/save
4.1.2 images do save, but rotated 90 degrees

**Comment by tibbi** [comment]
@Kingwad @mrvanes  if you are willing to help with debugging it please shoot a mail at hello@simplemobiletools.com. I could send you a test version which would show a message. You just tell me what is written on it, it should help. Thanks
