### ISSUE TITLE
All photos are taken with full zoom

### ISSUE THREAD

**Issue by Embridioum** [SimpleMobileTools/Simple-Camera#172]
Fresh install, latest version from F-Droid. All photos are taken with full zoom. Have tried a bunch of different resolutions, but they all work the same. Sony Xperia XZ1 Compact with Open Camera installed and stock camera disabled.

**Comment by pelmato** [comment]
Same here on Xperia X Compact.

**Comment by tibbi** [comment]
So during the capture you still the proper preview, just the captured images are fully zoomed in? How about if you try zooming in somewhere around 50% with gestures, is the image still fully zoomed in to 100%?

**Comment by pelmato** [comment]
Changing the zoom makes the captured image correct. So this is a temporary workaround: just zoom in and then zoom out. After doing so all photos will be correct (until relaunching the application).

**Comment by tibbi** [comment]
alright, Ill probably be able to fix it properly then. Thanks

**Comment by pelmato** [comment]
Ok, I confirm it works now. Thank you !
