### ISSUE TITLE
Video's are saved 90° clockwise

### ISSUE THREAD

**Issue by mrvanes** [SimpleMobileTools/Simple-Camera#200]
Just like #171 video's aren't rotated correctly. Was not able to encounter this until #170 was fixed (for which thanks, by the way!!)

**Comment by mrvanes** [comment]
Actually, the picture rotation isn't solved completely: Only landscape pictures are OK, portrait pics are rotated still?

**Comment by tibbi** [comment]
not sure, there are many different cameras and manufacturers, I guess it still isnt fixed completely reliably

**Comment by godfuture** [comment]
When I save the picture to internal storage, portrait is fine. Saving to SD card it is rotated 90°.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
