### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [SimpleMobileTools/Simple-Camera#210]
screenshot

https://mega.nz/#!uvAUAQLB

key: 

LgL48SEvpb6PNDbjYtU7tKgxj9bjKoTaZlYpuZBal9Q

**Comment by tibbi** [comment]
upload images directly please, not via some third party services.

**Comment by unknowtech** [comment]
how do I put it on github? thank

**Comment by tibbi** [comment]
just drag and drop it

**Comment by unknowtech** [comment]
![screenshot_20190102-231131](https://user-images.githubusercontent.com/41585567/50615316-51401f80-0ee4-11e9-802d-f629eabf879b.jpg)

**Comment by shadow00** [comment]
+1, I get the exact same error on a Huawei Y6 2016, using the latest version (5.1.1) from f-droid

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
