### ISSUE TITLE
Black screen in picture mode for the back camera only

### ISSUE THREAD

**Issue by johnwilkins128** [SimpleMobileTools/Simple-Camera#212]
Hi,

Android 8.1...I get a black screen, without any error messages, for the back camera only. Front one works fine and video mode works fine for both cameras. any idea how to fix it?

**Comment by tibbi** [comment]
what app version do you have?

**Comment by johnwilkins128** [comment]
v 4.2.0

**Comment by tibbi** [comment]
that is an ancient version, update to 5.0.0 please

**Comment by lkraav** [comment]
5.0.2: I'm experiencing exact same thing as original poster. Also Android 8.1, albeit on an exotic platform (Sailfish OS)

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
