### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by dybxin** [SimpleMobileTools/Simple-Camera#218]
Output:  C:\Users\Dell\Desktop\ziliao\Simple-Camera\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:131: error: unescaped apostrophe in string
"All'\avvio apri la fotocamera posteriore".
C:\Users\Dell\Desktop\ziliao\Simple-Camera\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:131: error: not a valid string.
C:\Users\Dell\Desktop\ziliao\Simple-Camera\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:143: error: unescaped apostrophe in string
"La fotocamera 猫 utilizzabile sia per catturare foto che per registrare video. Si pu貌 cambiare fra fotocamera posteriore e anteriore, modificare il percorso di salvataggio e limitare la risoluzione. Il flash pu貌 essere abilitato o disabilitato, oppure utilizzato come torcia. Si possono utilizzare le dita per modificare l'ingrandimento.

        Si pu貌 avviare questa applicazione premendo il tasto fisico della fotocamera, per fare ci貌 猫 possibile di aver bisogno di disabilitare la fotocamera incorporata nel sistema, andando in Impostazioni 鈫� Applicazioni 鈫� Fotocamera 鈫� Disabilita.

        L\'applicazione non contiene pubblicit脿 o permessi non necessari; 猫 completamente opensource e la si pu貌 personalizzare con i propri colori preferiti.

        Questa 猫 solamente una delle tante applicazioni della serie Simple Mobile Tools. Si possono trovare le altre su https://www.simplemobiletools.com".
C:\Users\Dell\Desktop\ziliao\Simple-Camera\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:135: error: not a valid string.
C:\Users\Dell\Desktop\ziliao\Simple-Camera\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:246: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Command: C:\Users\Dell\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\e2a4b842c8cd814aa10e7f760be61043\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        C:\Users\Dell\Desktop\ziliao\Simple-Camera\app\build\intermediates\res\merged\debug \
        C:\Users\Dell\Desktop\ziliao\Simple-Camera\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #1

**Comment by tibbi** [comment]
should be fixed already
