### ISSUE TITLE
Can't use this code to my apps

### ISSUE THREAD

**Issue by Shivani12345** [SimpleMobileTools/Simple-Camera#226]
I am using this code to my application and gradle  "com.simplemobiletools:commons:5.13.10" .But i got toast"you are using fake version of the app.For your own safety download the original one from site.thanks". help me

**Comment by tibbi** [comment]
Commons is not supposed to be used by other apps

**Comment by aarifroshan** [comment]
how can this issue be resolved, facing same issue.
