### ISSUE TITLE
Landscape mode not fuctioning properly

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-Camera#228]
When I use portrait mode, it seems fine, but when I go into landscape, the viewfinder view is still vertical, although the camera view is now horizontal.

**Comment by kllkko** [comment]
Hi bro,I found the same question,have you solve this problem? could you give me some suggestions ,thanks

**Comment by puppykickr** [comment]
@kllkko 
Not yet.
There are many apps in the Simple Mobile Tools collection, and some have been keeping the dev busy.

**Comment by kllkko** [comment]
Thanks a lot,I have solved it,just modify one line code in setupCameraOutput() in CameraPreview.kt , then it will be working 


mActivity.runOnUiThread {
                    //mTextureView.setAspectRatio(mPreviewSize!!.height, mPreviewSize!!.width)
                    mTextureView.setAspectRatio(mPreviewSize!!.width, mPreviewSize!!.height)
  }

**Comment by tibbi** [comment]
umm, no.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
