### ISSUE TITLE
confusion with horizontal reversing for front camera

### ISSUE THREAD

**Issue by roynico** [SimpleMobileTools/Simple-Camera#230]
I'm a bit confused with the feature "reverse horizontally pictures  for front camera":
* When the option is NOT checked -> the pictures taken with the front camera are left-right switched (I would expect the converse)
* When the option IS checked -> the pictures are left-right correct, but 180° rotated!

**Comment by tibbi** [comment]
it should work as flipping, not rotating. There are many camera related device-specific glitches though, not sure when will it be fixed.
