### ISSUE TITLE
Images saved with wrong rotation if exif metadata switched off

### ISSUE THREAD

**Issue by ccaccb** [SimpleMobileTools/Simple-Camera#234]
Somehow since v5.1.0 images taken in portrait mode on my phone are saved 90 deg right rotated. This seems to be connected to the "Safe photo exif metadata" setting, which I used to have disabled.

I take landscape mode images by rotating my phone 90 deg left, because that feels natural to me, but I tested both variants. Landscape mode seems to be detected corretly (at least the icons are rotating when tilting the phone).

I am assuming landscape images should be saved such that a photo of e.g. a document with text taken in landscape mode can be read normally in portait mode.

||exif ON | exif OFF |
|---|---|---|
|Portait| :heavy_check_mark: | :x: image rotated 90 deg right |
|Landscape (rotate phone 90 deg left)| :heavy_check_mark:   | :heavy_check_mark:  |
|Landscape (rotate phone 90 deg right)| :heavy_check_mark: | :x: image rotated 180 deg |

As a workaround I can enable the use of exif metadata but I'd rather prefer the images to be rotated correctly without the need to write any metadata.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
