### ISSUE TITLE
Allow taking pictures on locked device

### ISSUE THREAD

**Issue by rti** [SimpleMobileTools/Simple-Camera#24]
This is a feature request.

I would like to activate the camera using e.g. double power button press on a locked device. This works, but the device still asks to unlock, which is a bit inconvenient. 

Might help: open camera [1] implements it and names the setting "Show camera when locked"

[1] https://sourceforge.net/p/opencamera/code/ci/master/tree/

**Comment by Klimmbimmel** [comment]
That would be very helpful

**Comment by tradej** [comment]
+1. This is the last feature that's keeping the app from being perfect in my book. I've donated some, I hope it helps.

**Comment by tibbi** [comment]
added in 3.2.0
