### ISSUE TITLE
Focus is fixed after using manual focus

### ISSUE THREAD

**Issue by herrenP** [SimpleMobileTools/Simple-Camera#240]
Using version 5.1.1 of the app on my Samsung S8+ (although with LOS16 and not Samsung's official ROM) I experience that I can focus manually once only. After that the focus seem to be fixed. I can neither refocus manually or use autofocus.

A work around is to switch between video and photo mode.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
