### ISSUE TITLE
Error when starting video

### ISSUE THREAD

**Issue by gerhardbeck** [SimpleMobileTools/Simple-Camera#246]
Hi, I tried to start a video capture, but had the following Error:
java.lang.IllegalArgumentException: Surface was abandoned.

Obviously it didn't start to take a video.

It's an Android 9

**Comment by tibbi** [comment]
what app version are you using?

**Comment by gerhardbeck** [comment]
5.1.1., yesterday installed from f-droid

**Comment by youkii** [comment]
Hi, i have the same error when trying to start a video capture.

Same error message as described above by gerhardbeck, an empty mp4 file is created in the DCIM folder.
Version 5.2

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
