### ISSUE TITLE
Preview and image mismatch

### ISSUE THREAD

**Issue by sciurius** [SimpleMobileTools/Simple-Camera#251]
When taking pictures, the picture actually taken does not match the image on the screen.

This is a screenshot of what the app shows me. Note that it looks vertically compressed.

![Screenshot of what the app shows me](https://user-images.githubusercontent.com/1118804/71558086-790e8880-2a4f-11ea-8f3a-ab03a628f543.jpg)

This is the picture that is taken. It lacks a substantial part on the top and bottom.

![Actual picture taken](https://user-images.githubusercontent.com/1118804/71558180-998b1280-2a50-11ea-87cb-93dc7158d565.jpg)

Samsung A3 (2017), Android 8.0.0.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
