### ISSUE TITLE
Cannot save video recording always say "Video recording failed, try using different resolution".

### ISSUE THREAD

**Issue by Gamemulatorer** [SimpleMobileTools/Simple-Camera#252]
![Screenshot_20200101-100108](https://user-images.githubusercontent.com/37603562/71637432-4b5b5680-2c7e-11ea-9c8f-cf4664f341fe.png)

### Logcat
[simple_camera_log.txt](https://github.com/SimpleMobileTools/Simple-Camera/files/4013722/simple_camera_log.txt)
### Device Specs
[DevCheck-Specifications.txt](https://github.com/SimpleMobileTools/Simple-Camera/files/4013723/DevCheck-Specifications.txt)

Im using v5.1.1

**Comment by Emulatorer** [comment]
I tried all the resolution but still failed to save video please fixed this issue 🙏

#happynewyear

**Comment by Emulatorer** [comment]
@tibbi any update? 😅

**Comment by tibbi** [comment]
not really

**Comment by Emulatorer** [comment]
@tibbi where I can download the beta version of this app? or there's a automated build for beta apk?

**Comment by tibbi** [comment]
what beta version? What do you expect having there?

**Comment by Emulatorer** [comment]
Just for testing purposes :)

**Comment by Emulatorer** [comment]
Issue still happen
