### ISSUE TITLE
Gallery isn't properly updated if pictures are stored on an external sd-card

### ISSUE THREAD

**Issue by Rolf185** [SimpleMobileTools/Simple-Camera#261]
Hi,
I'm using LinageOS 16 (Android 9). I've set the default storage location to external-sd/DCIM/Camera (in Detail: /storage/0FB2-1510/DCIM/Camera). The camera app works fine. New pictures are stored there but they aren't properly shown in the gallery. My filemanager shows the new pictures in  /storage/0FB2-1510/DCIM/Camera and the pictures are fine. But the gallery app shows an empty gray placeholder instead. Everything is ok after a reboot. And everything works fine if I use a storage location on internal storage.
I've looked for this issue and found solutions like "Trigger a media rescan" which is automated executed during reboot.  So, may be the camera app doesn't trigger a media rescan for the external sd card storage location?

Thanks,
Rolf

**Comment by tibbi** [comment]
Ye that could be the case. The Camera can have quite a few other device specific issues too that are hard to reproduce or fix so it isnt really a priority for now.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
