### ISSUE TITLE
togglePhotoVideo too slow,how to make it faster?

### ISSUE THREAD

**Issue by kllkko** [SimpleMobileTools/Simple-Camera#262]
togglePhotoVideo too slow,how to make it faster?thanks

  18:57:26.804 7980-7980/  I/System.out: ltlt initVideoMode closeCamera start
  18:57:28.124 7980-7980/  I/System.out: ltlt initVideoMode closeCamera end,openCamera start
  18:57:29.063 7980-7980/  I/System.out: ltlt initVideoMode openCamera end

  18:57:51.065 7980-7980/  I/System.out: ltlt initPhotoMode closeCamera start
  18:57:52.283 7980-7980/  I/System.out: ltlt initPhotoMode closeCamera end,openCamera start
  18:57:53.106 7980-7980/  I/System.out: ltlt initPhotoMode openCamera end

it takes more then 2 seconds

**Comment by tibbi** [comment]
well the app doesnt work properly on some devices, there are many things done differently per manufacturer. It needs a big rewrite but it wont happen anytime soon.

**Comment by kllkko** [comment]
> well the app doesnt work properly on some devices, there are many things done differently per manufacturer. It needs a big rewrite but it wont happen anytime soon.

ok,thanks a lot

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
