### ISSUE TITLE
Recent media on Simple Camera shows media from other folders

### ISSUE THREAD

**Issue by AlanSmythe** [SimpleMobileTools/Simple-Camera#268]
This issue is a bit difficult to explain and I apologize if this might be a duplicate. But I am having an issue. It is in regards to the square at the bottom of Simple Camera top right options.

Somehow, Simple Camera can see other media folders and will display whatever is most recent . For example, if I were to take a screenshot on my phone, and then use Simple Camera, it would not see the last image or video I took using Simple Camera as most recent, it would always show the screenshot.

I would like for an update so that Simple Camera can only see media in the folder I choose for it to save too. I do not want media from other folders on my phone to be displayed on Simple Camera no matter if it is the most recent.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
