### ISSUE TITLE
Removing the Settings button via intent

### ISSUE THREAD

**Issue by niccokunzmann** [SimpleMobileTools/Simple-Camera#269]
Hi,

I am writing an [app which allows children to paint](https://github.com/niccokunzmann/coloring-book/).
Part of it is generating outline images from photos.
As I remembered your app, I was wondering if I could 
1. call it via intent to return a picture
2. remove the unnecessary UI features which take kids out of the flow

I am sure about (1) that I can open it to take a picture.
I would like to remove the settings button however, to make it even simpler.

My question is that if I would implement (2) - which I think may not be implemented, yet - would you guide me or merge the PR and release a new version in some future?

**Comment by tibbi** [comment]
well just capture an image and open it in Simple Draw or somewhere, I dont see why would such features be needed in a Camera app. Thanks
