### ISSUE TITLE
No preview ?

### ISSUE THREAD

**Issue by Hydro8** [SimpleMobileTools/Simple-Camera#272]
Hi

Does simple-camera comes with preview of last capture ?

I only see one picture at the bottom of the settings icon but it's not the preview of the last capture, it's an image of simple-gallery from another folder.

Thank

**Comment by Hydro8** [comment]
It's never the right image :/

**Comment by bellegarde-c** [comment]
Same here, it seems photo are not registered to Android media database.

In Signal, I can share photos from GCam but not from Simple Camera.

**Comment by anddam** [comment]
> Same here, it seems photo are not registered to Android media database.

I am experiencing this as well, not sure if it belongs in this issue or not.

I noticed that pictures taken with Camera are not present in Google Photos until I open them, e.g. with Files. Then they are displayed in Photos and known to the media database.

**Comment by anddam** [comment]
Also see #268 that possibly has the same cause.

**Comment by shanemd** [comment]
I am also experiencing this issue. Here are some details from my phone:

1. In camera mode, no preview is displayed. However, pressing on the place where the preview should be brings up an image viewer, but no image is displayed.
2. In video mode, a preview is displayed, but it's from a random directory not related to the simple camera app. Pressing on it correctly brings up a video player with the video shown in the preview.
3. In both cases, the preview (or invisible preview 'button'), are only displayed after pressing the settings button, opening the settings 'drawer'.

Happy to share more info if it will help solve this issue.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
