### ISSUE TITLE
java io file not found exception

### ISSUE THREAD

**Issue by NicolasDesvignes** [SimpleMobileTools/Simple-Camera#276]
When i shoot a picture, got this message and picture not really saved…
Last 5.1 version work, more recent won't…
![Screenshot_20200531-195846](https://user-images.githubusercontent.com/29175515/83359376-20cf1000-a37a-11ea-8c1a-ba6260468b32.png)

**Comment by tibbi** [comment]
where are you saving the files? What have you set in the app settings?

**Comment by NicolasDesvignes** [comment]
In sd card, i set up correctly
Perfectly work on 5.1 release

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
