### ISSUE TITLE
Video recording is lag and not focus

### ISSUE THREAD

**Issue by Gamemulatorer** [SimpleMobileTools/Simple-Camera#278]
### Camera logs
[camera-logs-2020-06-13-17-08-09.zip](https://github.com/SimpleMobileTools/Simple-Camera/files/4774347/camera-logs-2020-06-13-17-08-09.zip)

Android 6.0.1
Mali-450 GPU
Camera v5.2.1 github apk

**Comment by tibbi** [comment]
you mean that the video is freezing and focus doesnt work?

**Comment by Gamemulatorer** [comment]
> you mean that the video is freezing and focus doesnt work?

Not freezing only lag and yes focus doesn't work correctly.
