### ISSUE TITLE
"An error ocurred: java.lang.IllegalStateException failed to get surface"

### ISSUE THREAD

**Issue by JamesKristofUbiarco** [SimpleMobileTools/Simple-Camera#280]
This happens when I try to take video from the app in my moto g6

**Comment by abald124** [comment]
Experiencing the same issue on a Samsung Tab Active 2

**Comment by dorrisowens** [comment]
Man just go to video option and lower the video resolution. It will work. By default video resolution is set to highest which will not work. Just lower it and it will work.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
