### ISSUE TITLE
Camera crashes/freezes when being opened from lockscreen

### ISSUE THREAD

**Issue by Wurzelmann** [SimpleMobileTools/Simple-Camera#281]
When opened from the lockscreen (in my case by a button shortcut), the camera works on the first time, but every time afterwards, it just freezes and shows the interface with a black screen. After manually killing the app, it works again once and then the freezing starts again.

Opening the camera from the launcher works every time, no problem there.

Device: OnePlus 3T
OS: LineageOS 17.1-20200720-nightly-oneplus3

**Comment by gitwah** [comment]
Can confirm this behavior. On my device, launching the camera from the lockscreen results in a completely black camera preview with the (unresponsive) UI on top of it. Unlike OP, manually killing the app doesn't help, it never seems to work.

Device: One Plus 7 Pro
OS: LineageOS 18.1, Android 11

**Comment by hamishmb** [comment]
Confirmed on Moto G8 Power with Stock Android 11.

**Comment by Wurzelmann** [comment]
New phone, same problem:

Device: OnePlus 5T
OS: 18.1-20220426-NIGHTLY-dumpling

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this

**Comment by hamishmb** [comment]
Please wait until I've confirmed the fix.

**Comment by Wurzelmann** [comment]
Same problem persists, sorry to say. :-/

**Comment by hamishmb** [comment]
Yeah, let's not get hasty and close all the open bugs. I'm going to go through and try and reproduce some of them soon.

Don't get me wrong, I really like the new UI and it seems much better :)

**Comment by hamishmb** [comment]
Interestingly, it's working for me. I'm still on the same device with Android 11. What are you running, Wurzelmann?

**Comment by Wurzelmann** [comment]
Same device (OnePlus 5T), but Android 12 now (19-20221011-NIGHTLY-dumpling).

**Comment by tibbi** [comment]
havent you uninstalled the stock camera? The current behaviour doesnt seem to be related to Simple Camera at all

**Comment by Wurzelmann** [comment]
I had not, but disabled it now and you're right, Simple Camera is working when Stock Camera is disabled. Strange behaviour, but at least we know the culprit now. Thank you for your support, closing now.

**Comment by hamishmb** [comment]
Ah, that explains why it works for me too then.

Should we add a note somewhere for this?

**Comment by tibbi** [comment]
no, that isnt actually related to our app at all

**Comment by hamishmb** [comment]
It is though, because people will assume your app is broken if they aren't told they need to disable the built-in camera.

**Comment by hamishmb** [comment]
My bad, it says in the readme. Is this information presented to users on first launch?

**Comment by tibbi** [comment]
no

**Comment by hamishmb** [comment]
Okay, I'll file a new issue for that then.
