### ISSUE TITLE
Option to turn off shutter sound

### ISSUE THREAD

**Issue by shanemd** [SimpleMobileTools/Simple-Camera#284]
I love the simplicity of this app, but I find myself not using it because of the shutter sound. It would be nice to be able to turn it off.

**Comment by tibbi** [comment]
You can do it in the app settings. If it doesnt work, it is probably limited by the system. Does turning it off work in any other downloaded camera app?

**Comment by shanemd** [comment]
Ah, I found it now. Thank you! I was confused by the settings button. I thought the two icons it revealed were all of the settings, and didn't realize that pressing the settings icon again would open up a full settings page.
