### ISSUE TITLE
Suggestion: Don't use black as the override background color.

### ISSUE THREAD

**Issue by BrendonIrwan** [SimpleMobileTools/Simple-Camera#286]
Set the resolution to anything less than your screen (e.g. 1:1), the override background color is black. Taking pictures of very dark subjects this way can be very difficult since you can't tell which black portion is part of the viewfinder and which is part of said background.

Alternatively you can implement an overlay grid, or any sort of visual cues as to where the viewfinder borders.

**Comment by tibbi** [comment]
I dont really plan changing that, pretty much all apps use black there
