### ISSUE TITLE
Video Not Working 

### ISSUE THREAD

**Issue by dorrisowens** [SimpleMobileTools/Simple-Camera#287]
Hello, I am using version 5.2.1 while photos works okay but when I click on record video option I get this error
![Screenshot_20200924-183149_Camera](https://user-images.githubusercontent.com/71829524/94148417-3ec60080-fe94-11ea-8c18-db70b2d5d734.jpg)
![Screenshot_20200924-183147_Camera](https://user-images.githubusercontent.com/71829524/94148437-438ab480-fe94-11ea-867d-6f8676485170.jpg)

Please help me out. java.lang.IllegalStateException: Failed to get surface and java.io.IOException: Prepare Failed are two errors I am facing.

Device : Samsung Galaxy A10
Android Version : 10

**Comment by dorrisowens** [comment]
Did You Find Any Fix for this dev ?

**Comment by tibbi** [comment]
no, sadly that app can have many issues depending on your device, not sure when will I be able to fix them.

**Comment by dorrisowens** [comment]
Ok , I will test it on multiple devices. I have Samsung, Xiaomi and oneplus device. If issue is on all three then I will Inform you.

**Comment by dorrisowens** [comment]
Okay, I will wait for fix. If you need any help like logcat or multiple device test then just comment here.

**Comment by dorrisowens** [comment]
Hello dev, I found the problem. You have set default video resolution to be highest 3264 × 1836 which my device didn't support. On lowering resolution It works.

**Comment by dorrisowens** [comment]
I recommend that in new update try to keep default resolution a little lower.

**Comment by tibbi** [comment]
well then it shouldnt list it as an available resolution :/ Ill keep an eye on it. Thanks

**Comment by dorrisowens** [comment]
I dont know but it didnt work on avaliable highest resolution. BTW thanks for replying :)
