### ISSUE TITLE
Issue with webp images

### ISSUE THREAD

**Issue by sdicke** [SimpleMobileTools/Simple-Camera#289]
I observed the following behavior:
1. Open a folder containing webp images
2. Click on an image in that folder
3. The image get opened regulary
4. Change images within the single image view mode
5. After view times, a Android warning popup appears, which informs me, that that app would have problems (in German: „Galerie bleibt ständig stehen“).
6. I close the dialog popup
7. After repeat step 2, the dialog of step 5 appears, the app get closed instantly
8. Open the app anew
9. Execute step 2
10. See step 7

This behavior is reproducible.

**Comment by tibbi** [comment]
what app version are you using?
