### ISSUE TITLE
Android 10 issues flash light and last pic preview

### ISSUE THREAD

**Issue by andycandy-de** [SimpleMobileTools/Simple-Camera#290]
I found some issues with android 10.
The flash light doen't work proper in auto-mode and on-mode

- *auto-mode*: there is no flashlight in lowlight scene
- *on-mode*: the flashlight is just *on*, but there is no extra brighter flash light when taking pictures

I compared the flash light behavior with two different android versions. The flashlight reacts with a older android version as expected.

Furthermore the last picture preview seems to be buggy and sluggish with android 10. I noticed that sometimes the preview shows an older picture (not the last captured) and somtimes no picture is shown.

**Comment by tibbi** [comment]
Im not aware of any way of making a flashlight brighter, it can only be turned on or off. Maybe only preinstalled apps can change the intensity, those usually have more permissions than casual downloaded apps. Report 1 thing per issue please.
