### ISSUE TITLE
[Pixel 4a] View finder of the rear camera is very laggy, shows images twice or more

### ISSUE THREAD

**Issue by ericschdt** [SimpleMobileTools/Simple-Camera#293]
Source: F-Droid
Version: Version 5.2.3
Phone: Google Pixel 4a

The viewfinder was supposed to show a keyboard, however that what it looks like:
![IMG_20201208_181527](https://user-images.githubusercontent.com/43318127/101518184-7b74a480-3979-11eb-8b68-4da5bbf6cfeb.jpg)

When I move the camera I find that the image is updated on a very slowly rate, often with those duplicate compositions. Other apps like OpenCamera work fine.

For the front camera everything works as expected.

**Comment by Fellhahn** [comment]
I'm seeing identical behaviour on the Pixel 4 XL running CalyxOS.

On the Pixel 4 XL, there are two rear cameras, a 12 MP standard and a 16 MP tele. In Open Camera, these are not surfaced as two different cameras that you can select using the multiple cameras button. Rather when you zoom past a certain limit (2.0x in this case) you are automatically switched from the standard to the tele. (A stupid implementation to be sure).

I have noticed that while Simple Camera will behave incorrectly when first opened and using the standard lens, if i zoom in, forcing the (camera/app/OS?) to use the second sensor, everything behaves normally.

Looking at the specs of the 4 XL, the standard camera is listed as "Dual-Pixel PDAF" while the tele simply says "PDAF" .

Possibly this split image view is a product of trying to communicate with a dual-pixel PDAF sensor.

**Comment by boggle247** [comment]
Having the same issue as OP with my pixel 4a running calyxos as well. Stock camera app, opencamera, and Google camera all work fine.

I'd love to use this app bc it's the only one with built in support to remove exif data.

**Comment by JustACasual** [comment]
Same here on Pixel 4a with stock Android 12.
Unusable unfortunately.

Thanks for your great work with those simple mobile tools btw. Using some of them and also donated ;)

**Comment by tibbi** [comment]
app has been rewritten since then
