### ISSUE TITLE
Multi Camera Access on Moto G Stylus 

### ISSUE THREAD

**Issue by metalx1000** [SimpleMobileTools/Simple-Camera#294]
Running Simple-Camera v5.2.3
The Moto G Stylus has 3 back camera's:
1) Standard
2) Macro
3) Action Camera

I'm unable to access the 2 of the 3 back cameras (I can only access the standard camera on the back and the front camera) .
I understand that some manufacturers restrict the access to some cameras,
But I'm able to access all camera using FreeDcam (another open source camera app).
If FreeDcam can access the camera, I would think Simple-Camera could as well.

Let me know if there is any other information I can get you to help figure this out.
Thank you

```
Device manufacturer: motorola
Device model: moto g stylus
Device code-name: qcom
Device variant: sofiap
```

**Comment by tibbi** [comment]
dont really expect having a fix for it, such issues are really device specific. And already reported somewhere. Thanks though
