### ISSUE TITLE
[Feature request] Add support for camera api v2

### ISSUE THREAD

**Issue by ReduxGB** [SimpleMobileTools/Simple-Camera#297]
The camera api V2 has increased reliability and is more stable on some devices compared to camera api (v1?). On my device (Samsung galaxy A5, running lineage OS), I have trialed different camera apps, open camera has the same issues related to the camera completely stopping working but after switching the camera api to v2 (in app settings) it worked fine without issues. I believe this would fix many of the issues users are currently experiencing but I cannot be certain.

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
