### ISSUE TITLE
Can't take a picture

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [SimpleMobileTools/Simple-Camera#299]
## Metadata
**Version : 5.3.1**
**Android Version : 8.0.0**
**Phone : Honor 7A AUM-L29**

## Description
When I take a picture, I get this error message : 
`Capture picture android.hardware.camera2.CameraAccessException.CAMERA_ERROR (3): submitRequestList:283: Camera 0: Got error Invalid argument (-22) after trying to submit capture request`

## Screenshot

(in french « une erreur est survenue » = "an error occured")
<details>

![Screenshot_20210613-212016_1](https://user-images.githubusercontent.com/24496705/121820424-f1dcc100-cc92-11eb-8902-b592b9e28b44.jpg)

</details>

**Comment by tibbi** [comment]
try restarting your device

**Comment by SCOTT-HAMILTON** [comment]
I tried but it didn't work, I get the same error. I think the problem isn't with this app though because the stock huawei camera app doesn't work either. I did some cleaning and uninstalled some system apps. I will try to reinstall huawei mobile services.

**Comment by tibbi** [comment]
well, it wont be our issue then indeed

**Comment by SCOTT-HAMILTON** [comment]
I tried a factory reset to fix the stock camera app. But it didn't work, so I tried Open Camera and it seems to work.
