### ISSUE TITLE
Recorded videos are corrupted

### ISSUE THREAD

**Issue by alexcoder04** [SimpleMobileTools/Simple-Camera#305]
Hi, taking videos does not work properly for me (photos are working fine).

The videos are recorded without any errors, but cannot be opened afterwards (I tried Simple Gallery, VLC on Android and mpv on Linux, but none of them managed to open the file properly). A video of about 10 seconds length is reported to have a length of -57:-18 or -596:31:21, depending on the video player.

App version: 5.3.1 (from F-Droid)
Android version: 10
Device: Samsung Galaxy M20

**Comment by alexcoder04** [comment]
Furthermore, the problem seems to be with the video stream: if I try to play the file in mpv, the audio plays properly for the time the video should be and the player exits while the picture freezes.

I get the following output in mpv:
```
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Invalid SampleDelta -519998700 in STTS, at 0 st:0
 (+) Video --vid=1 (*) (h264 3264x1836)
 (+) Audio --aid=1 --alang=eng (*) (aac 1ch 8000Hz)
AO: [pulse] 8000Hz mono 1ch float
VO: [gpu] 3264x1836 yuv420p
AV: 00:00:00 / 596:31:23 (0%) A-V:  0.492 Dropped: 89

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:11 / 596:31:23 (0%) A-V:  0.000 Dropped: 274

Exiting... (End of file)
```

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
