### ISSUE TITLE
Can duplicate file names if photos snapped in quick succession

### ISSUE THREAD

**Issue by hamishmb** [SimpleMobileTools/Simple-Camera#334]
I assume this isn't completely abandoned if there are still commits? I can't see any other FOSS camera apps on F-Droid, at any rate.

If you snap multiple photos in very quick succession, they can be named "x" and "x (1)" where x is a timestamp. I guess it would be good to just use numbers rather than timestamps, or to use more precise timestamps or something?

**Comment by tibbi** [comment]
there is currently no public version of the app, it is being remade

**Comment by hamishmb** [comment]
Good to know it is being remade, thanks :)
