### ISSUE TITLE
Can't save to sd card

### ISSUE THREAD

**Issue by arthurhawron** [SimpleMobileTools/Simple-Camera#353]
Just started using this app, tried changing storage location to a folder in my sd card. It then asks to allow access to the root directory of the sd card, but android does not allow file access there. Just wondering if there is any fix or workaround. Android version 13, Device: redmi note 11 pro

**Comment by tibbi** [comment]
where did you get the app from? What version are you using?

**Comment by arthurhawron** [comment]
> where did you get the app from? What version are you using?

I'm using v 5.3.1 from F-Droid

**Comment by tibbi** [comment]
that is an ancient app version, a new one will be released soon.
