### ISSUE TITLE
Change resolution for photo like in 5.3.1

### ISSUE THREAD

**Issue by makerpat** [SimpleMobileTools/Simple-Camera#373]
It is not possible to change the resolution in 5.4.3. 
I liked it, because i use this app to take photos for documetation in low resolution without need to resize it after.
Please bring it back or i will stay @ 5.3.1 ;)

![simple_camera](https://user-images.githubusercontent.com/59851356/202797645-3717de8c-5f31-46b3-9d88-3644b8cd9f2d.jpg)

**Comment by tibbi** [comment]
that isnt on the roadmap now
