### ISSUE TITLE
Can't run project with Android Studio on Mac OS

### ISSUE THREAD

**Issue by vunhiem96** [SimpleMobileTools/Simple-Camera#376]
Could not find com.github.SimpleMobileTools:Simple-Commons:0525fb316c. I run it on windows computer it's completely normal, on macbook i get this error. Your other projects all run ok on my macbook

<img width="1851" alt="Ảnh chụp Màn hình 2022-11-22 lúc 23 17 04" src="https://user-images.githubusercontent.com/28688600/203365673-45f7b805-868f-41c8-bb91-714ddd945e1e.png">

**Comment by tibbi** [comment]
it works just fine, maybe just jitpack was down
