### ISSUE TITLE
sd card folder not used for video

### ISSUE THREAD

**Issue by paolo-caroni** [SimpleMobileTools/Simple-Camera#397]
I use simple camera app with saving folder on my sd card.
For image save on the selected folder, but if I try to make a video, save on internal DCIM folder, with an error message that inform me of the change of saving folder.

app version: 5.6.0

**Comment by tibbi** [comment]
what OS version are you using?

**Comment by paolo-caroni** [comment]
Lineageos 19 aka android 12.

**Comment by Anke** [comment]
Same problem here since the latest Simple Camera update. I'm using /e/OS 1.6 (=Android 11)
