### ISSUE TITLE
Private by default camera (EXIF)

### ISSUE THREAD

**Issue by staticdev** [SimpleMobileTools/Simple-Camera#399]
Hi @tibbi, I am really glad we have these amazing Simple Apps and also happy we can [enable/disable EXIF](https://github.com/SimpleMobileTools/Simple-Camera/issues/39). One suggestion I have is to make it *disabled by default* to protect user privacy. I think it should be opt-in since today many people share photos without thinking if they are sharing location or phone data in it. This default already exist in other camera apps such as Libre Camera. If you agree I am happy to make my first PR to the project.

**Comment by tibbi** [comment]
not really, I dont plan adding that. There is no location in the photos. Thanks though

**Comment by staticdev** [comment]
@tibbi not 100% sure if you understood what I suggested. There is nothing to add, instead just come with the toggle off by default. Even if there is no location it is still phone metadata that should not be shared if the used to not want or thing about that.

**Comment by tibbi** [comment]
I dont want to disable it by default

**Comment by barrelful** [comment]
Always good to see the attitude of the main developer of an app towards privacy of it's users. Just lost my install and star in you repo with this one. I will also start recommending other apps to my colleagues.
