### ISSUE TITLE
How, as developers, can we help you to support more devices?

### ISSUE THREAD

**Issue by xfarrow** [SimpleMobileTools/Simple-Camera#404]
Nowadays smartphones have `n` different cameras altogether, and it's difficult to keep up with it. I was wondering if as a developer I can help you to support more devices, if needed and wanted of course.

If some companies release the source code for their APIs maybe we can help you integrate them.

**Comment by tibbi** [comment]
well, not sure, the situation is getting worse so I dont think it will ever work right. It would be a full time job for multiple devs.
