### ISSUE TITLE
[Feature Request] Hold to record, as in Whatsapp

### ISSUE THREAD

**Issue by Terkyz** [SimpleMobileTools/Simple-Camera#408]
A very useful and mechanical function of Whatsapp, is that if I'm on the camera and I hold the take photo button, instead of taking a photo and stop (as is the case of Simple Camera) or take a burst of photos until I release the button, is that it automatically records, this seems to me a great feature that I wish it was in Simple Camera if it could be.

**Comment by tibbi** [comment]
dont really expect having it here
