### ISSUE TITLE
Photos taken in Landscape appear as Portrait in all Gallery Apps

### ISSUE THREAD

**Issue by Starcr0ss** [SimpleMobileTools/Simple-Camera#412]
Hi,
When I take a photo in landscape in Simple Camera v5.6.2, the photo appears in gallery apps as portrait. This does not happen in the default Motorola camera app. I have a Moto G Stylus 2021.
Here is an example photo.
![IMG_20230513_174323](https://github.com/SimpleMobileTools/Simple-Camera/assets/26168814/c9e64662-83e4-40d5-90a8-38f3134db1cd)

**Comment by tibbi** [comment]
how does it work in other downloaded galleries?

**Comment by Starcr0ss** [comment]
> how does it work in other downloaded galleries?

Here it is in Simple Gallery, Google Photos, and Camera Roll X
![Simple_Gallery](https://github.com/SimpleMobileTools/Simple-Camera/assets/26168814/67725ad2-d3b5-4173-a1cd-fc36f8772d31)
![Google_Photos](https://github.com/SimpleMobileTools/Simple-Camera/assets/26168814/4e32ffbe-ff9d-4301-82cb-73be91af0012)
![CameraRollX](https://github.com/SimpleMobileTools/Simple-Camera/assets/26168814/6c5ab731-5a07-4923-bf00-e3ea78c3b91f)

**Comment by tibbi** [comment]
so the issue apparently isnt with our app, it is in the way file rotation is stored

**Comment by Starcr0ss** [comment]
Very interesting, the problem seems to no longer occur in V5.6.3!
