### ISSUE TITLE
Just some praise

### ISSUE THREAD

**Issue by summersab** [SimpleMobileTools/Simple-Camera#421]
I wanted to leave some praise for this app. I am a LineageOS user, and one of the features it has is the ability to block system access to the camera and microphone via Quick Settings toggles. When apps try to access these devices while they are blocked, the user receives a standard Android permission request, and the devices are unlocked.

While the built-in camera in LineageOS asks for camera access when it is opened, it unfortunately doesn't ask for access to the microphone when starting a video recording. This has resulted in me forgetting to unblock my microphone and taking many videos (some of them important family events) without audio.

I tried a few other camera apps from F-Droid, and they have the same behavior. However, Simple Camera DOES check and ask for microphone permissions before starting to record video, so I switched to your app by default.

Thank you again for your work! Very well done.

**Comment by tibbi** [comment]
thanks, enjoy :) (but I'll close this anyway)
