### ISSUE TITLE
Old Android support request.

### ISSUE THREAD

**Issue by lastlos** [SimpleMobileTools/Simple-Camera#442]
I'm using an Android 7.1.1. I degoogled my own phone and I'm instead of Google using SimpleMobileTools apps but my launcher and camera still Google's. I decided use Simple Keyboard, Simple Camera and Simple Launcher -beacuse they are perfect for me- but i cant. I think if you make old version support the project will earn more support. The old apps is not better than now's. Please support old Android versions.

**Comment by tibbi** [comment]
not really, it isnt on th eroadmap
