### ISSUE TITLE
Controls should not rotate when phone is laid flat

### ISSUE THREAD

**Issue by platypro** [SimpleMobileTools/Simple-Camera#55]
Whenever the phone is laid flat, the view always resets to portrait, even if already in landscape. This is a usability issue for people who wish to take landscape photos facing down (such as from a book). The user needs to rotate the photo afterwards to keep its required orientation.

**Comment by Klimmbimmel** [comment]
This means you want a button (or something similar) to fix the orientation. (As simple-camera can't arbitrary interpret orientation information from the system.)

Why don't you put the book prone/biased?

**Comment by tibbi** [comment]
camera has been rewritten from scratch in 5.4.0, so Im closing this
