### ISSUE TITLE
Use Camera2 API on Android 5 and greater due to Camera deprecation

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Camera#59]
Reference: https://developer.android.com/reference/android/hardware/camera2/package-summary.html

**Comment by tibbi** [comment]
i wont change it anytime soon as I dont want to maintain 2 codebases, but I can leave it here for the future

**Comment by cryptomilk** [comment]
I think most phones offer a HAL3 now. So it would be nice to have an app supporting API2 will allows you to do much more settings, like ISO, AWB or EV control.

Also it would allow to load QCOM extensions/filters.

See:

https://source.codeaurora.org/quic/la/platform/packages/apps/SnapdragonCamera/tree/src/com/android/camera/imageprocessor/filter?h=camera.lnx.3.0.r2-rel

**Comment by tibbi** [comment]
The app will be using Camera2 from version 4.1
