### ISSUE TITLE
camera flash inverted?

### ISSUE THREAD

**Issue by 0142929** [SimpleMobileTools/Simple-Camera#65]
when camera flash is on, it light continuously

**Comment by tibbi** [comment]
Theres 3 modes. On, off, auto. Its always on with the "on" mode, thats correct. You might want to use the Auto mode.

**Comment by 0142929** [comment]
i see, so this is normal.
thank you.

**Comment by tibbi** [comment]
yes, auto mode wasnt good enough for taking photos in the dark, as the short flash wasnt enough for the camera to focus properly.

**Comment by 0142929** [comment]
me did not think about it.
you are right, it is better :)
