### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by Michele64** [SimpleMobileTools/Simple-Camera#69]
Would be nice to have it as an option

**Comment by tibbi** [comment]
that requires location permission which many people wouldnt like, but I might add it as an option in the future

**Comment by Michele64** [comment]
Thanks, maybe switched off by default so that android's request kicks in only when turning it on?

**Comment by tibbi** [comment]
thats how it would work on Android 6+, but it would always be on on Android 4 and 5

**Comment by Michele64** [comment]
You're right, and thanks for considering it

**Comment by Yang-zLab** [comment]
I love simple camera, I use it as my work camera. It can save the photos to another diraction, so I can seperate photos for work from my personal daliy life photos. It can choose a lower resolution so the space of the phone can be saved. The only thing I am looking forward to see is the GPS metadata. If the location could be recorded, this app is perfect for work usage.

**Comment by alecpetrosky** [comment]
Yes, completely agreed that this funcion is very handy for sorting out photos years later.

**Comment by inson1** [comment]
I dont like giving more permissions than is necessary

**Comment by Michele64** [comment]
but it would be the user's choice. And without that functionality many users will abandon the app, possibly frustrated because they realize it much later that their pictures lack an essential information....

**Comment by inson1** [comment]
I get it. But there should be more opinions.

And I never used it and I dont like giving to message, photo more informations than needed.

I love options, but its also unsafe even as options.

Cloud drive storages and other software LOVES metadata.

And there are many things in backlog already.

What I am trying to say is that I would like to see more other things before. And If there is everything done then maybe then.

But thats my opinion. 1 vs 5

**Comment by Saijin-Naib** [comment]
Yep, I have stopped using it because of this.

**Comment by tibbi** [comment]
geolocation has actually been added already, so closing it. It is disabled by default and the app doesnt have location permission without toggling the setting and granting the Location permission.
