### ISSUE TITLE
Do we have a  parameter manual adjustment in this demo？

### ISSUE THREAD

**Issue by butterl** [SimpleMobileTools/Simple-Camera#70]
Hi , 

I'm trying to test night photo alg and manually taking many photos ,it's just not effective .
So I find this excelent demo，and wandering if we have a  parameter manual adjustment  selection in it, 
Like Shutter time，focal length， white balance etc. ?

**Comment by tibbi** [comment]
Hey no, Im not setting any of those, everything is handled by the camera itself under the hood. I dont think Ill be adding the option to change those values anytime soon.
