### ISSUE TITLE
File upload shortcut - picturemode

### ISSUE THREAD

**Issue by nektor211** [SimpleMobileTools/Simple-Camera#79]
Hello,

Could you please add an option to go directly to the picture camera (not video) when using file upload (like in html file input field)? Now it's posible to open camera for taking videos and change to picture mode, but it would be nice to be able to go picture/photo mode directly.
![screenshot_20171021-162430_](https://user-images.githubusercontent.com/1188728/31853002-cd4f2808-b681-11e7-9901-337edc7c6e4a.png)

**Comment by tibbi** [comment]
it happens only at VIDEO_CAPTURE intents, which is supposed to return a video. That's why you see the Camcorder app at a selection too. I dont want to change that behaviour. The Camera is set to photo mode only if the website requests a photo, it works fine.

**Comment by nektor211** [comment]
Thank you for the explanation, I've fixed the web form (by adding `capture="camera" accept="image/*"` in case anyone else comes accross this issue) and it works fine.
