### ISSUE TITLE
Couldn't rename Error

### ISSUE THREAD

**Issue by lulalala** [SimpleMobileTools/Simple-Camera#86]
Version 2.4.1

Android 7.0
Kernel version 2.18.14-11528205

After taking a photo, the following error message appears:
The photo persists correctly though.
Note the error message has spelling errors as well "Could'nt"

![1508831596_screenshot_201710](https://user-images.githubusercontent.com/366910/31930827-a7c1df8c-b8d3-11e7-9647-4a034b5573f5.png)

**Comment by tibbi** [comment]
the typo comes from google, its not my strings :)

**Comment by tibbi** [comment]
it should be fixed in the next version released today

**Comment by lulalala** [comment]
I just tested on 3.0.1 and the same error still persists.

**Comment by tibbi** [comment]
ye some others reported it too

**Comment by tibbi** [comment]
should be fixed already
