### ISSUE TITLE
Cropped back camera picture

### ISSUE THREAD

**Issue by Aiurek** [SimpleMobileTools/Simple-Camera#92]
Moto G4 plus
Android 7.0
Simple camera v2.4.1 (F-Droid)
Back camera resolution set to 4608 x 2592 (11.9 MP, 16:9)

When taking pictures using my back camera, not the complete area, visible in the camera view, is safed. Instead, I get an  image which is cropped on all four sides. The front camera works fine.

![sci](https://user-images.githubusercontent.com/27865200/32376735-ed14bd82-c0a5-11e7-91d6-b00557d25b97.jpg)

**Comment by tibbi** [comment]
The Camera has been rewritten from scratch under the hood in version 4.1.0, please update whenever it becomes available and create a new ticket if you are still having issues.
