### ISSUE TITLE
Can't Save to External SD Card 

### ISSUE THREAD

**Issue by RandolphNimmer** [SimpleMobileTools/Simple-Camera#95]
seeing "open failed: EACCESS (permission denied)" toast when trying to take pictures after setting save directory to SD card location. I think you may have not included the WRITE EXTERNAL STORAGE permission in your app? 

I'm on an S4 with android 4.4.2

**Comment by tibbi** [comment]
it is included, SD cards just arent handled properly on Android 4.4. Google made it really difficult to handle them, I havent found any way of solving it yet as I dont have a device for reproducing it.

**Comment by F3000** [comment]
@tibbi is that possible on Android 7/8 ?

**Comment by tibbi** [comment]
well it should work there, are you getting the error?

**Comment by F3000** [comment]
Oh sooty . I have set up the wrong settings

**Comment by tibbi** [comment]
it should be fixed in the next version for Android 5+, I cannot fix it for lower ones.
