### ISSUE TITLE
Some date/time related EXIF values are missing

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Camera#98]

**Comment by ergeka** [comment]
Hello,
I try simple camera and it's a good tool.
But I discover that no EXIF of DATE/TIME and camera model ! :-(
And I wan't use it because I want these EXIF info ...
Sorry.
Gérard.

**Comment by tibbi** [comment]
do you have "Save photo exif metadata" enabled in app settings? What version do you have?

**Comment by ergeka** [comment]
Hi,
Thanks for the fast reponse ;-)
- the option is enabled 
- the version is 4.0.0
Gérard.

**Comment by kolAflash** [comment]
Same problem for me.

Simple Camera: 4.0.0 ("_Save photo exif metadata_" is enabled)
Phone: FairPhone 2
OS: LineageOS-14.1

**Comment by ergeka** [comment]
Hi,

It's working fine now; the EXIF are correct !
Thanks ;-)

Gérard.
